# 8 Advanced Data Structures  

In [1]:
%load_ext pymatbridge

C:\Anaconda3\lib\site-packages\IPython\nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)


Starting MATLAB on ZMQ socket tcp://127.0.0.1:3839
Send 'exit' command to kill the server
......MATLAB started and connected!


## 8.1 Cell arrays  

In [2]:
%%matlab
c = {[3 2 1], 'I love MATLAB'}


c = 

    [1x3 double]    'I love MATLAB'



In [3]:
%%matlab
d = {'Why do' ,'I love MATLAB?', c}


d = 

    'Why do'    'I love MATLAB?'    {1x2 cell}



## 8.2 Structs  

In [6]:
%%matlab
clear z
z.particle = 'electron'
z.position = [2 0 3]
z.spin = 'up'


z = 

    particle: 'electron'


z = 

    particle: 'electron'
    position: [2 0 3]


z = 

    particle: 'electron'
    position: [2 0 3]
        spin: 'up'



In [8]:
%%matlab
z(2,3).particle = 'proton'
z(2,3).position = 'unknown'


z = 

2x3 struct array with fields:

    particle
    position
    spin


z = 

2x3 struct array with fields:

    particle
    position
    spin



In [9]:
%%matlab
z = struct ( ...
  'particle', {'electron',[],[] ;
  [],[],'proton' }, ...
  'position', {[2 0 3], [],[] ;
  [],[],'unknown'}, ...
  'spin', {'up', [],[] ;
  [],[],[]}) ;

## 8.3 Sets  

```
ismember     test membership, x ∈ A
intersect    set intersection, A ∩ B
union        set union, A ∪ B
setdiff      set difference, A \ B
unique       removes duplicates from a set
setxor       (A ∪ B) \ (A ∩ B)
issorted     checks if a set is sorted
```

In [10]:
%%matlab
A = [1 2 5 6 8 8 9]
B = [1 2 3 5 7]
ismember(3,A)   % 0
ismember(3,B)   % 1
intersect(A,B)  % [1 2 5]
setdiff(A,B)    % [6 8 9]
union(A,B)      % [1 2 3 5 6 7 8 9]
setxor(A,B)     % [3 6 7 8 9]
unique(A)       % [1 2 5 6 8 9]


A =

     1     2     5     6     8     8     9


B =

     1     2     3     5     7


ans =

     0


ans =

     1


ans =

     1     2     5


ans =

     6     8     9


ans =

     1     2     3     5     6     7     8     9


ans =

     3     6     7     8     9


ans =

     1     2     5     6     8     9



## 8.4 Other data types  

In [12]:
%%matlab
A = ones(3,4)
B = rand(3,4)
C = cat(3, A, B)


A =

     1     1     1     1
     1     1     1     1
     1     1     1     1


B =

    0.8147    0.9134    0.2785    0.9649
    0.9058    0.6324    0.5469    0.1576
    0.1270    0.0975    0.9575    0.9706


C(:,:,1) =

     1     1     1     1
     1     1     1     1
     1     1     1     1


C(:,:,2) =

    0.8147    0.9134    0.2785    0.9649
    0.9058    0.6324    0.5469    0.1576
    0.1270    0.0975    0.9575    0.9706

